add normalize.css, styles buttons - primary, secondary, alternate
js-tasks-ru/htmlcss-20240216_akoesnikova pull request #4
Opened 2024-02-28 20:54 UTC by Lika1100

2024-02-28 20:54 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-04 21:41 UTC, GSemikozov requested changes

2024-03-05 22:19 UTC, GSemikozov approved these changes

2024-03-05 22:19 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2024-03-05 22:21 UTC, GSemikozov approved these changes

2024-03-05 22:21 UTC, merged