accordion
js-tasks-ru/htmlcss-20240216_akoesnikova pull request #5
Opened 2024-03-01 08:23 UTC by Lika1100

2024-03-01 08:24 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-03 20:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-04 14:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-04 21:42 UTC, GSemikozov requested changes

2024-03-04 21:42 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    max-width: 579px;
лишнее ограничение

2024-03-04 21:42 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 24px 32px;
когда .accordion__item[open] - паддинг снизу 32

2024-03-04 21:42 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +        <details class="accordion__item">
элементы не могут существовать вне своего блока, так что все элементы надо завернуть в общий div с классом блока

2024-03-05 18:57 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-05 19:08 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-05 19:25 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-05 22:22 UTC, GSemikozov requested changes
все ок, только конфликт надо поправить

2024-03-06 21:58 UTC, closed without merging