histogram
js-tasks-ru/htmlcss-20240216_akoesnikova pull request #9
Opened 2024-03-06 20:37 UTC by Lika1100

2024-03-06 20:38 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-06 20:45 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-11 15:46 UTC, GSemikozov requested changes

2024-03-11 15:46 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__container {
какая-то сложная реализация)
должно быть:
```
display: flex;
gap: 1px;
align-items: flex-end;
```

2024-03-11 15:46 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__link a {
margin-top: 3px;

2024-03-11 15:46 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    display: flex;
margin-bottom: 39px

2024-03-11 15:46 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +            <div class="column" style="height: 50px;"></div>
у родителя фикс высота (50px), а здесь уже в процентах

2024-03-14 10:31 UTC, GSemikozov requested changes

2024-03-14 10:31 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.column {
.histogram__column? и вместо width - flex-basis: 9px

2024-03-14 10:31 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    justify-content: space-between;
лишнее

2024-03-20 21:55 UTC, GSemikozov approved these changes

2024-03-20 21:55 UTC, merged